topics:
  - /camera1/camera1/color/camera_info
  - /camera1/camera1/color/image_raw
  - /camera1/camera1/aligned_depth_to_color/image_raw
  # - /camera1/camera1/depth/color/points
  - /livox/lidar
  - /livox/imu
  # - /dlio/odom_node/pose
