name: Build GroundTruth3D Containers

on:
  push:
    tags:
      - 'dev*'
      - 'v*'

jobs:

  # Stage 0: Check conditions and set variables
  get-version:
    runs-on: ubuntu-latest

    outputs:
      image_version: ${{ steps.set_version.outputs.image_version }}

    permissions:
      packages: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image version
        id: set_version
        run: |
          echo "image_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT


  # Stage 1: GroundTruth3D images (AMD64/x86)
  GroundTruth3D_AMD64:
    needs: get-version
    name: GroundTruth3D Images (AMD64)
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        config:
          - { build_context: '.devcontainer', image_name: 'ground_truth3d_base', image_version: "${{ needs.get-version.outputs.image_version }}" }
          # - { build_context: '.devcontainer/amd64_x86_without_GPU', image_name: 'wheelchair2_no_gpu', image_version: "${{ needs.get-version.outputs.image_version }}" }
    uses: ./.github/workflows/build-workflow.yaml
    with:
      build_context: ${{ matrix.config.build_context }}
      image_name: ${{ matrix.config.image_name }}
      image_version: ${{ matrix.config.image_version }}
      runs_on: ubuntu-22.04

# Stage 1: Wheelchair images (Jetson/ARM)
# wheelchair2_ARM64:
#   needs: get-version
#   name: Wheelchair2 Images (ARM64)
#   permissions:
#     packages: write
#     contents: read
#   strategy:
#     matrix:
#       config:
#         - { build_context: '.devcontainer/jetson-arm', image_name: 'wheelchair2_jetson', image_version: "${{ needs.get-version.outputs.image_version }}" }
#   uses: ./.github/workflows/build-workflow.yaml
#   with:
#     build_context: ${{ matrix.config.build_context }}
#     image_name: ${{ matrix.config.image_name }}
#     image_version: ${{ matrix.config.image_version }}
#     runs_on: ubuntu-22.04-arm

  # Stage 2: Create release
  # if the tag is v*, create a pre-release
  create-release:
    needs: [GroundTruth3D_AMD64]
    if: startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          prerelease: true
          generateReleaseNotes: true